spring.application.name=backend-service

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=airs

server.port=8080

logging.level.com.airs.backendservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
